-- Smoke test for the Lua RE2-subset engine.
package.path = "../src/?.lua;" .. (package.path or "")
local re = require("regex")

local passed, total = 0, 0
local function check(pat, input, expect, label)
  total = total + 1
  local got = re.re_test(pat, input)
  if got == expect then
    passed = passed + 1
  else
    io.stderr:write(string.format("FAIL %s: /%s/ on %q expected %s got %s\n",
      label, pat, input, tostring(expect), tostring(got)))
  end
end

check("hello", "say hello world", true, "literal")
check("^cat", "cat sat", true, "^anchor")
check("^cat", "a cat", false, "^anchor miss")
check("end$", "the end", true, "$anchor")
check("end$", "ended here", false, "$anchor miss")
check("^abc$", "abc", true, "both")
check("^abc$", "xabc", false, "both miss")
check("^a.c$", "abc", true, ".")
check("^a.c$", "ac", false, ". needs char")
check("^ab*c$", "ac", true, "*zero")
check("^ab*c$", "abbbc", true, "*many")
check("^ab+c$", "ac", false, "+miss")
check("^ab+c$", "abc", true, "+one")
check("^colou?r$", "color", true, "?zero")
check("^colou?r$", "colour", true, "?one")
check("^a{3}$", "aaa", true, "{n}")
check("^a{3}$", "aa", false, "{n} less")
check("^a{2,4}$", "aaa", true, "{n,m}")
check("^a{2,4}$", "a", false, "{n,m} less")
check("^a{2,4}$", "aaaaa", false, "{n,m} more")
check("^a{2,}$", "aa", true, "{n,}")
check("^a{2,}$", "aaaa", true, "{n,} more")
check("^[abc]$", "a", true, "class")
check("^[abc]$", "d", false, "class miss")
check("^[^xyz]$", "a", true, "neg class")
check("^[^xyz]$", "x", false, "neg class miss")
check("^[0-9]+$", "123", true, "range")
check("^[0-9]+$", "12a", false, "range miss")
check("^\\d{3}$", "123", true, "\\d")
check("^\\d{3}$", "abc", false, "\\d miss")
check("^\\w+$", "abc_123", true, "\\w")
check("^\\w+$", "hi there", false, "\\w miss")
check("^a\\sb$", "a b", true, "\\s space")
check("^a\\sb$", "a\tb", true, "\\s tab")
check("^a\\sb$", "ab", false, "\\s miss")
check("^\\D+$", "abc", true, "\\D")
check("^\\D+$", "a1", false, "\\D miss")
check("^(cat|dog)$", "cat", true, "alt")
check("^(cat|dog)$", "fish", false, "alt miss")
check("^(?:ab|cd)+$", "ab", true, "non-cap +")
check("^(?:ab|cd)+$", "abcd", true, "non-cap + two")
check("^(?:ab|cd)+$", "abc", false, "non-cap miss")
check("^a(bc)+d$", "abcd", true, "cap + once")
check("^a(bc)+d$", "abcbcd", true, "cap + twice")
check("\\bword\\b", "a word here", true, "\\b")
check("\\bword\\b", "sword", false, "\\b inside")
check("\\bword\\b", "word!", true, "\\b punct")
check("^a\\.b$", "a.b", true, "escaped .")
check("^a\\.b$", "aXb", false, "escaped . strict")
check("^a.*?b$", "ab", true, "lazy zero")
check("^a.*?b$", "aXXXb", true, "lazy many")
check("[aA][bB][cC]", "ABc", true, "the canonical case")
check("[aA][bB][cC]", "DEf", false, "the canonical neg")

io.write(string.format("Lua regex engine: %d/%d passed\n", passed, total))
os.exit(passed == total and 0 or 1)
